import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getFirestore, collection, onSnapshot } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { firebaseConfig, COLLECTION_NAME } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getFirestore(app);let all=[];let active='all';let keyword='';
const labels={'dat-nen':'Đất nền','nha-pho':'Nhà phố','can-ho':'Căn hộ','nha-vuon':'Nhà vườn','dat-nong-nghiep':'Đất nông nghiệp','nghi-duong':'BĐS nghỉ dưỡng','du-an':'Dự án'};
const grid=document.getElementById('propertyGrid'), empty=document.getElementById('emptyState');
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function render(){const data=all.filter(x=>x.status!=='tam-an'&&(active==='all'||x.category===active)&&(!keyword||`${x.title||''} ${x.location||''}`.toLowerCase().includes(keyword)));grid.querySelectorAll('.property-card').forEach(x=>x.remove());data.forEach(x=>{const el=document.createElement('article');el.className='property-card';el.dataset.type=x.category||'';el.dataset.name=x.title||'';el.innerHTML=`<div class="property-image"><img loading="lazy" src="${esc(x.image||'assets/images/video-poster.jpg')}" alt="${esc(x.title)}"><span class="tag">${x.status==='da-ban'?'Đã bán':x.status==='da-coc'?'Đã cọc':'Đang chào bán'}</span><button class="heart" type="button"><i class="fa-regular fa-heart"></i></button></div><div class="property-body"><span class="property-type">${labels[x.category]||esc(x.category)}</span><h3>${esc(x.title)}</h3><div class="location"><i class="fa-solid fa-location-dot"></i>${esc(x.location)}</div><div class="features"><span><i class="fa-solid fa-ruler-combined"></i>${esc(x.area)}</span><span><i class="fa-solid fa-file-shield"></i>${esc(x.legal)}</span></div><div class="price-row"><span class="price">${esc(x.price)}</span><span class="detail-link">Xem chi tiết →</span></div></div>`;el.onclick=()=>openDynamic(x);el.querySelector('.heart').onclick=e=>{e.stopPropagation();const i=e.currentTarget.querySelector('i');i.classList.toggle('fa-regular');i.classList.toggle('fa-solid')};grid.insertBefore(el,empty)});empty.style.display=data.length?'none':'block'}
onSnapshot(collection(db,COLLECTION_NAME),snap=>{all=snap.docs.map(d=>({id:d.id,...d.data()}));render()},()=>render());
document.querySelectorAll('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{active=btn.dataset.filter;document.querySelectorAll('.filter-btn').forEach(b=>b.classList.toggle('active',b===btn));render()}));
window.searchProperties=()=>{active=document.getElementById('typeFilter')?.value||'all';keyword=(document.getElementById('keyword')?.value||'').trim().toLowerCase();render();document.getElementById('properties').scrollIntoView({behavior:'smooth'})};
function lines(s){return String(s||'').split(/\r?\n|•/).map(x=>x.trim()).filter(Boolean).map(x=>`<li>${esc(x)}</li>`).join('')}
function yt(url=''){const m=url.match(/(?:youtu\.be\/|youtube\.com\/(?:shorts\/|watch\?v=|embed\/))([\w-]{6,})/);return m?m[1]:''}
function openDynamic(x){document.querySelector('#propertyModal .property-type').textContent=`${labels[x.category]||x.category||''} · ${x.status==='da-ban'?'Đã bán':x.status==='da-coc'?'Đã cọc':'Đang chào bán'}`;document.querySelector('#propertyModal .detail-info h3').textContent=x.title||'';document.querySelector('#propertyModal .detail-price').textContent=x.price||'';const badges=document.querySelector('#propertyModal .detail-badges');badges.innerHTML=`<span><i class="fa-solid fa-ruler-combined"></i> ${esc(x.area)}</span><span><i class="fa-solid fa-location-dot"></i> ${esc(x.location)}</span><span><i class="fa-solid fa-file-shield"></i> ${esc(x.legal)}</span>`;document.querySelector('#propertyModal .detail-note').textContent=x.description||'';const imgs=(Array.isArray(x.images)?x.images:[]);if(x.image&&!imgs.includes(x.image))imgs.unshift(x.image);window.galleryImages=imgs.length?imgs:[x.image||'assets/images/video-poster.jpg'];window.currentLightboxIndex=0;document.getElementById('mainDetailImage').src=window.galleryImages[0];const gallery=document.querySelector('#propertyModal .gallery-grid');gallery.innerHTML=window.galleryImages.map((u,i)=>`<img loading="lazy" src="${esc(u)}" alt="${esc(x.title)} ${i+1}" onclick="openLightboxBySrc(this.src)">`).join('');const boxes=document.querySelectorAll('#propertyModal .detail-box ul');[x.traffic,x.utilities,x.resort,x.investment].forEach((v,i)=>{if(boxes[i])boxes[i].innerHTML=lines(v)});const id=yt(x.video);const wrap=document.querySelector('#propertyModal .video-wrap');wrap.innerHTML=id?`<div class="youtube-short"><iframe src="https://www.youtube.com/embed/${id}" title="${esc(x.title)}" loading="lazy" frameborder="0" allowfullscreen></iframe></div>`:'<p>Chưa có video.</p>';window.openPropertyDetail()}
