import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, collection, addDoc, updateDoc, deleteDoc, doc, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { firebaseConfig, COLLECTION_NAME } from "../js/firebase-config.js";
const app=initializeApp(firebaseConfig), auth=getAuth(app), db=getFirestore(app);let items=[];
const $=id=>document.getElementById(id), fields=['title','category','status','price','area','location','legal','image','images','video','map','description','traffic','utilities','resort','investment'];
const labels={'dat-nen':'Đất nền','nha-pho':'Nhà phố','can-ho':'Căn hộ','nha-vuon':'Nhà vườn','dat-nong-nghiep':'Đất nông nghiệp','nghi-duong':'BĐS nghỉ dưỡng','du-an':'Dự án'};
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value)}catch(err){$('loginError').textContent='Sai email hoặc mật khẩu.'}});
$('logoutBtn').onclick=()=>signOut(auth);onAuthStateChanged(auth,user=>{if(user){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('userEmail').textContent=user.email;listen()}else{$('loginView').classList.remove('hidden');$('appView').classList.add('hidden')}});
function listen(){onSnapshot(collection(db,COLLECTION_NAME),snap=>{items=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));render()})}
function render(){const q=$('searchInput').value.toLowerCase(),cat=$('filterCategory').value;const list=items.filter(x=>(cat==='all'||x.category===cat)&&(!q||`${x.title||''} ${x.location||''}`.toLowerCase().includes(q)));$('propertyList').innerHTML=list.length?list.map(x=>`<div class="property-row"><img src="${esc(x.image||'../assets/images/video-poster.jpg')}" onerror="this.src='../assets/images/video-poster.jpg'"><div><h3>${esc(x.title||'Chưa có tiêu đề')}</h3><div><span class="badge">${labels[x.category]||x.category||'Khác'}</span><span class="badge">${esc(x.status||'dang-ban')}</span></div><div class="meta">${esc(x.price||'Chưa có giá')} · ${esc(x.area||'')} · ${esc(x.location||'')}</div></div><div class="row-actions"><button data-edit="${x.id}">Sửa</button><button class="danger" data-delete="${x.id}">Xóa</button></div></div>`).join(''):'<div class="form-card">Chưa có bất động sản phù hợp.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete))}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function showForm(editing=false){$('listView').classList.add('hidden');$('formView').classList.remove('hidden');$('pageTitle').textContent=editing?'Sửa bất động sản':'Thêm bất động sản'}function showList(){$('formView').classList.add('hidden');$('listView').classList.remove('hidden');$('pageTitle').textContent='Danh sách bất động sản'}
function reset(){ $('propertyForm').reset();$('docId').value='';$('status').value='dang-ban'}
function edit(id){const x=items.find(i=>i.id===id);if(!x)return;reset();$('docId').value=id;fields.forEach(f=>{$(f).value=f==='images'?(Array.isArray(x.images)?x.images.join('\n'):x.images||''):x[f]||''});$('featured').checked=!!x.featured;showForm(true)}
async function remove(id){if(confirm('Xóa bất động sản này?'))await deleteDoc(doc(db,COLLECTION_NAME,id))}
$('propertyForm').addEventListener('submit',async e=>{e.preventDefault();const data={};fields.forEach(f=>data[f]=f==='images'?$(f).value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean):$(f).value.trim());data.featured=$('featured').checked;data.updatedAt=serverTimestamp();if(!data.image&&data.images.length)data.image=data.images[0];try{if($('docId').value)await updateDoc(doc(db,COLLECTION_NAME,$('docId').value),data);else{data.createdAt=serverTimestamp();await addDoc(collection(db,COLLECTION_NAME),data)}$('formMessage').textContent='Đã lưu thành công.';reset();showList()}catch(err){$('formMessage').textContent='Lỗi: '+err.message}});
$('addBtn').onclick=()=>{reset();showForm()};$('cancelBtn').onclick=showList;document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active'));b.classList.add('active');b.dataset.view==='form'?(reset(),showForm()):showList()});$('searchInput').oninput=render;$('filterCategory').onchange=render;
